### ISSUE TITLE
Differences when using cholesky

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#90]
When cholesky is disabled in SCF, two things happen:

1. SCF takes twice as long to complete.
2. Final energies are different from the ones using Cholesky; in fact, they have a low numerical precission and randomly vary around 10 Hartree.

Should we attempt to fix this or just marry Cholesky and provide a separate SQS matrix?

**Comment by ramirezfranciscof** [comment]
If I am not mistaken, the code use to diagonalize S to obtain either Xsym or Xcan. Now we are using "a different Xcan" which has the benefit of being triangular, with a two step process of cholesky diagonalization and an inversion. The problem is that right now that doesn't allow us to obtain the eigenvalues, but I believe that we could use an SVD decomposition instead of the inversion that would allow us to recover them. I will be reviewing this subject soon and try to make a comparison of costs for the different methods.

**Comment by fedepedron** [comment]
Wasn't this fixed in #181?

**Comment by ramirezfranciscof** [comment]
Yes, I think so.
